enter_Name=input('please enter you name')
print('Enter name:',enter_Name)
print('(H)ello''\n(G)oodbye''\n(Q)uit')
chose_F=input('please choose')
print(chose_F)
print('(H)ello''\n(G)oodbye''\n(Q)uit')
chose_s=input('please choose')
print(chose_s)
